FROM vonproteus/xamarin-android-docker

LABEL version="0.1.0"
LABEL name="MobileClassifierApp"
LABEL com.github.actions.icon="terminal"
LABEL com.github.actions.color="blue"

COPY LICENSE README.md /
ENTRYPOINT ["xabuild"]
CMD ["/help"]
